compile:
	 mpiCC -std=c++0x -L/home/andreas/Downloads/mpiP-3.4/lib -lmpiP -lm -lbfd -liberty -lunwind -I/usr/include/c++/4.7/ -o scheduler.run scheduler.cpp main.cpp

clean:
	rm -rf *.out
	rm -rf *.run
