BUILD_FILE=*.funky
OUT_FILE=test.run

compile:
	$(MAKE) -f ../../../scripts/Makefile.template compile BUILD_FILE=$(BUILD_FILE) OUT_FILE=$(OUT_FILE)

release:
	$(MAKE) -f ../../../scripts/Makefile.template release BUILD_FILE=$(BUILD_FILE) OUT_FILE=$(OUT_FILE)

clean:
	$(MAKE) -f ../../../scripts/Makefile.template clean BUILD_FILE=$(BUILD_FILE) OUT_FILE=$(OUT_FILE)

