polylib: c2p.c File Reference
c2p.c File Reference
#include <stdlib.h>
#include <polylib/polylib.h>
Defines
#define WS 0
Functions
int main ()
Define Documentation
#define WS 0
Definition at line 18 of file c2p.c.
Referenced by main().
Function Documentation
int main ()
Definition at line 23 of file c2p.c.
References Constraints2Polyhedron(), Domain_Free(), Matrix_Free(), Matrix_Print(), Matrix_Read(), matrix::NbColumns, P_VALUE_FMT, Polyhedron_Print(), and WS.