polylib: disjoint_union_sep.c File Reference
disjoint_union_sep.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <polylib/polylib.h>
Defines
#define WS 0
Functions
void AffContraintes (Polyhedron *p)
int main ()
Define Documentation
#define WS 0
Definition at line 36 of file disjoint_union_sep.c.
Referenced by main().
Function Documentation
void AffContraintes (Polyhedron * p)
Definition at line 40 of file disjoint_union_sep.c.
References polyhedron::next, p, P_VALUE_FMT, and Polyhedron_PrintConstraints().
int main ()
Definition at line 50 of file disjoint_union_sep.c.
References AffContraintes(), Constraints2Polyhedron(), Disjoint_Domain(), Domain_Free(), Matrix_Free(), Matrix_Read(), polyhedron::next, and WS.