polylib: ehrhart_upper_bound.c File Reference
ehrhart_upper_bound.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <polylib/polylib.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 25 of file ehrhart_upper_bound.c.
References compute_poly(), Ehrhart_Quick_Apx(), _enumeration::EP, FOREVER, free_evalue_refs(), Free_ParamNames(), Matrix_Free(), Matrix_Read(), mpolyhedron_inflate(), matrix::NbColumns, _enumeration::next, p, Polyhedron_Free(), Print_Domain(), print_evalue(), Read_ParamNames(), show_matrix, _enumeration::ValidityDomain, value_init, value_print, and value_read.