polylib: ehrhart_union.c File Reference
ehrhart_union.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <polylib/polylib.h>
Functions
void Union_Read (Polyhedron **P, Polyhedron **C, const char ***param_name)
void recurse (Polyhedron *C, const char **param_name, Enumeration *e, Value *pmin, Value *pmax, Value *p, int l)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 144 of file ehrhart_union.c.
References polyhedron::Dimension, Domain_Enumerate(), _enumeration::EP, FOREVER, _enumeration::next, p, Print_Domain(), print_evalue(), recurse(), s, Union_Read(), _enumeration::ValidityDomain, value_assign, value_init, and value_read.
void recurse (Polyhedron * C, const char ** param_name, Enumeration * e, Value * pmin, Value * pmax, Value * p, int l)
Definition at line 112 of file ehrhart_union.c.
References compute_poly(), polyhedron::Dimension, value_assign, value_clear, value_increment, value_init, value_le, and value_print.
Referenced by main().
void Union_Read (Polyhedron ** P, Polyhedron ** C, const char *** param_name)
Definition at line 26 of file ehrhart_union.c.
References Constraints2Polyhedron(), Matrix_Alloc(), Matrix_Free(), Matrix_Read(), Matrix_Read_Input(), matrix::NbColumns, polyhedron::next, Read_ParamNames(), and s.
Referenced by main().