polylib: errormsg.h File Reference
errormsg.h File Reference
Functions
void errormsg1 (const char *f, const char *msgname, const char *msg)
Function Documentation
void errormsg1 (const char * f, const char * msgname, const char * msg)
Definition at line 46 of file errormsg.c.
References Pol_status.
Referenced by AddConstraints(), AddRays(), align_context(), Chernikova(), Constraints2Polyhedron(), Disjoint_Domain(), DomainAddConstraints(), DomainAddRays(), DomainCost(), DomainDifference(), DomainIntersection(), DomainSimplify(), DomainUnion(), Empty_Polyhedron(), exist_points(), FindSimple(), Gauss4(), GaussSimplify(), hermite(), left_hermite(), Matrix_Alloc(), Matrix_Extend(), Matrix_Read(), Matrix_Read_Input(), Polyhedron2Constraints(), Polyhedron2Rays(), Polyhedron_Alloc(), Polyhedron_Copy(), Polyhedron_Image(), Polyhedron_Preimage(), Polyhedron_Scan(), PolyhedronLTQ(), Rays2Polyhedron(), Remove_Redundants(), right_hermite(), SatMatrix_Extend(), SimplifyConstraints(), SimplifyEqualities(), SMAlloc(), Stras_DomainSimplify(), SubConstraint(), Universe_Polyhedron(), Vector_Alloc(), and Vector_Read().