polylib: ext_ehrhart.h File Reference
ext_ehrhart.h File Reference
Functions
Enumeration * Domain_Enumerate (Polyhedron *D, Polyhedron *C, unsigned MAXRAYS, const char **pn)
void new_eadd (evalue *e1, evalue *res)
Function Documentation
Enumeration* Domain_Enumerate (Polyhedron * D, Polyhedron * C, unsigned MAXRAYS, const char ** pn)
Definition at line 702 of file ext_ehrhart.c.
References AffConstraints(), _evalue::d, Degenerate(), Disjoint_Domain(), DMUnion(), Domain_Free(), DomainDifference(), DomainIntersection(), ecopy(), emptyQ, _enumeration::EP, free_evalue_refs(), IncludeInRes(), new_eadd(), _Polyhedron_union::next, _enumeration::next, polyhedron::next, POL_ENSURE_FACETS, POL_ENSURE_VERTICES, Polyhedron_Enumerate(), _Polyhedron_union::pt, Remove_RedundantDomains(), _enumeration::ValidityDomain, value_assign, value_init, and value_zero_p.
Referenced by main(), Polyhedron_Image_Enumerate(), and Polyhedron_LexSmallerEnumerate().
void new_eadd (evalue * e1, evalue * res)
Definition at line 320 of file ext_ehrhart.c.
References _enode::arr, _evalue::d, ecopy(), new_eadd(), new_enode(), p, periodic, polynomial, ppcm1(), value_addto, value_assign, value_clear, value_divexact, value_gcd, value_init, value_multiply, value_notone_p, value_notzero_p, value_set_si, and value_zero_p.
Referenced by Domain_Enumerate(), and new_eadd().