polylib: param.h File Reference
param.h File Reference
Functions
const char ** Read_ParamNames (FILE *in, int m)
void Free_ParamNames (const char **params, int m)
Function Documentation
void Free_ParamNames (const char ** params, int m)
Definition at line 81 of file param.c.
Referenced by main().
const char** Read_ParamNames (FILE * in, int m)
Definition at line 31 of file param.c.
References m, PCHAR, and s.
Referenced by main(), and Union_Read().