polylib: polytest.c File Reference
polytest.c File Reference
#include <stdio.h>
#include <polylib/polylib.h>
Defines
#define WS 0
Functions
int main ()
Variables
char s [128]
Define Documentation
#define WS 0
Definition at line 22 of file polytest.c.
Referenced by main().
Function Documentation
int main ()
Definition at line 26 of file polytest.c.
References Constraints2Polyhedron(), Domain_Free(), DomainConvex(), DomainSimplify(), DomainUnion(), GaussSimplify(), left_hermite(), Matrix_Alloc(), Matrix_Free(), Matrix_Print(), Matrix_Product(), Matrix_Read(), matrix::NbColumns, matrix::NbRows, polyhedron::next, P_VALUE_FMT, Polyhedron2Constraints(), Polyhedron2Rays(), Polyhedron_Image(), Polyhedron_Not_Empty(), Polyhedron_Print(), PolyhedronLTQ(), right_hermite(), s, and WS.
Variable Documentation
char s[128]
Definition at line 24 of file polytest.c.
Referenced by echange_c(), echange_l(), main(), Matrix_Read(), Matrix_Read_Input(), Polyhedron_Preprocess2(), Read_ParamNames(), and Union_Read().