polylib: pp.c File Reference
pp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <polylib/polylib.h>
Defines
#define WS 0
Functions
int main ()
Define Documentation
#define WS 0
Definition at line 23 of file pp.c.
Referenced by main().
Function Documentation
int main ()
Definition at line 25 of file pp.c.
References Constraints2Polyhedron(), _Param_Polyhedron::D, polyhedron::Dimension, _Param_Domain::Domain, Domain_Free(), END_FORALL_PVertex_in_ParamPolyhedron, FORALL_PVertex_in_ParamPolyhedron, Matrix_Free(), Matrix_Read(), matrix::NbColumns, nbPV, matrix::NbRows, _Param_Polyhedron::nbV, _Param_Domain::next, matrix::p, P_VALUE_FMT, Param_Polyhedron_Free(), Polyhedron2Param_Domain(), Print_Domain(), Print_Vertex(), _Param_Polyhedron::Rays, Read_ParamNames(), value_print, value_zero_p, _Param_Vertex::Vertex, and WS.