polylib: Zpolytest.c File Reference
Zpolytest.c File Reference
#include <stdio.h>
#include <polylib/polylib.h>
Defines
#define WS 0
Functions
int main ()
Variables
char s [128]
Define Documentation
#define WS 0
Definition at line 25 of file Zpolytest.c.
Referenced by main().
Function Documentation
int main ()
Definition at line 29 of file Zpolytest.c.
References AffineHermite(), AffineSmith(), CanonicalForm(), Constraints2Polyhedron(), Domain_Free(), DomainConvex(), DomainUnion(), EmptyLattice(), EmptyZPolyhedron(), isEmptyLattice(), isEmptyZPolyhedron(), LatticeDifference(), LatticeImage(), LatticeIncludes(), LatticeIntersection(), LatticePreimage(), LatticeSimplify(), LatticeUnion_Alloc(), LatticeUnion_Free(), LatticeUnion::M, Matrix_Copy(), Matrix_Free(), Matrix_Print(), Matrix_Read(), ZPolyhedron::next, LatticeUnion::next, P_VALUE_FMT, Polyhedron2Constraints(), PrintLatticeUnion(), s, SolveDiophantine(), SplitZpolyhedron(), Vector_Free(), Vector_Print(), WS, ZDomain_Free(), ZDomainDifference(), ZDomainImage(), ZDomainIntersection(), ZDomainPreimage(), ZDomainPrint(), ZDomainSimplify(), ZDomainUnion(), ZPolyhedron_Alloc(), and ZPolyhedronIncludes().
Variable Documentation
char s[128]
Definition at line 27 of file Zpolytest.c.