compile:
	echo "Compiling."
	 $(MAKE) makefile compile
	 #$(MAKE) -C tmp

release:
	echo "Releasing"
	 $(MAKE) makefile release
#	 $(MAKE) -C tmp


clean:
	 echo "Cleaning up."
	 $(MAKE) makefile clean
